id: ID88618C8
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-17T13:21:49+00:00'
last_modified: '2022-06-15T17:39:16.812770+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W28969
  title: རྒྱ་བོད་ཚན་རྩལ་ལོ་ཙཱའི་གཞུང་ལུགས་ཀྱི་རྣམ་བཤད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '1720':
      image_group_id: I1KG22677
      title: Volume 1 of rgya bod tshan rtsal lo tsA'i gzhung lugs kyi rnam bshad
      total_pages: 316
      order: 1
      base_file: 1720.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
